[tool.black]
# Compromise between Black's default of 88 and wasting horizontal screen space.
# According to Black's style guide, line lengths greater than 100 cause issues
# for individuals with poor sight. So, 100 seems like the best bet here.
line-length = 100

[tool.isort]
profile = "isort"
