---
- name: install the latest version of ntp
  become: yes
  yum:
    name: ntp
    state: latest

- name: Add amazon ntp server to ntp.conf
  lineinfile:
    path: /etc/ntp.conf
    insertafter: EOF
    line: 'server 169.254.169.123 prefer iburst'
  become: yes

- name: Set timezone to UTC
  timezone:
    name: UTC
  become: yes

- name: Restart ntpd
  service:
    name: ntpd
    state: restarted
  become: yes
