---
- name: Adjust yum timeout
  lineinfile:
    path: /etc/yum.conf
    line: timeout=60

- name: Install Pre-requisites
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    # Needed to supply `keytool` and also to run the app server.
    - java-1.15.0-openjdk-devel
  become: true

- name: Create JMeter Service User
  user:
    name: "{{ remote_jmeter_user }}"
    shell: /bin/false
  become: true

- name: Create Directory Tree for '{{ remote_test_dir }}' 
  file: 
    path: "{{ remote_test_dir }}" 
    state: directory
    owner: "{{ remote_jmeter_user }}"
    group: "{{ remote_jmeter_user }}"
    mode: u=rwx,g=rx,o=rx

- name: Copy and Unpack JMeter
  unarchive: 
    src: "support/apache-jmeter-{{ jmeter_version }}.tgz"
    dest: "{{ remote_test_dir }}"

- name: Fix JMeter Executable Permissions
  file: 
    path: "{{ item }}"
    owner: "{{ remote_jmeter_user }}"
    group: "{{ remote_jmeter_user }}"
    mode: 0774
  with_items:
    - "{{ remote_jmeter_dir }}/bin/jmeter-server"
    - "{{ remote_jmeter_dir }}/bin/jmeter"

- name: Disable SSL for RMI(needed for JMeter 4.0 or later)
  copy: 
    src: "{{ jmeter_properties_file }}"
    dest: "{{ remote_jmeter_dir }}/bin"
    owner: "{{ remote_jmeter_user }}"
    group: "{{ remote_jmeter_user }}"
    mode: 0644
