---
- hosts: localhost
  tasks:
    - name: Download App Server
      maven_artifact:
        group_id: org.wildfly
        artifact_id: wildfly-dist
        version: 8.1.0.Final
        extension: tar.gz
        dest: /tmp/wildfly-dist.tar.gz

    - name: Download Blue Button Data Server WAR
      maven_artifact:
        # FIXME: Once the Blue Button CI server is available again, grab an actual bluebutton-server WAR.
        group_id: org.apache.wicket
        artifact_id: wicket-examples
        version: 7.2.0
        extension: war
        dest: /tmp/bluebutton-data-server.war

- hosts: docker_container
  tasks:
    - name: Apply Ansible Role
      include_role:
        name: karlmdavis.bluebutton_data_server

    # Most of the differences between test cases are the variables used, so we pull them in with a test-case-specific include.
    - name: Set Ansible Variables for Test Case
      include_vars: "{{ lookup('env','TEST_CASE') }}.yml"

