name: Permissions Advisor

# set base permissions just to read
permissions:
  actions: read

# create inputs for workflow dispatch
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'The name of the workflow file to analyze'
        required: true
        type: string
      count:
        description: 'How many last runs to analyze'
        required: false
        type: string
        default: "10"

# execute advisor on inputs
jobs:
  advisor:
    runs-on: ubuntu-latest
    steps:
    - uses: GitHubSecurityLab/actions-permissions/advisor@v1
      with:
        name: ${{ inputs.name }}
        count: ${{ fromJSON(inputs.count) }}
